# Generated by Django 4.2.5 on 2024-02-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognitionbasedidentificationsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognitionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_video', models.ImageField(default='No Video', upload_to='FaceRecognitionVideo/')),
            ],
        ),
    ]
